"""Add leave types

Revision ID: 4ce50908caac
Revises: f4a6dba9c0cc
Create Date: 2025-01-09 10:52:42.495910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce50908caac'
down_revision = 'f4a6dba9c0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('menstrual_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('family_care_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('family_care_days')
        batch_op.drop_column('menstrual_days')
        batch_op.drop_column('personal_days')

    # ### end Alembic commands ###
