"""Add days column to LeaveRecord

Revision ID: f4a6dba9c0cc
Revises: 
Create Date: 2025-01-05 01:23:37.128646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4a6dba9c0cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Float(), nullable=False))
        batch_op.alter_column('reason',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('receipt_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_record', schema=None) as batch_op:
        batch_op.alter_column('receipt_url',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('days')

    # ### end Alembic commands ###
